### ISSUE TITLE
Win rates in dashboard graph are halved

### ISSUE THREAD

**Issue by riQQ** [HearthStats/hearthstats#428]
see screen shot
![hearthstats_bug](https://cloud.githubusercontent.com/assets/3404787/5607967/d446bada-9470-11e4-8891-9736e59d1abe.PNG)

**Comment by trigun0x2** [comment]
Hey those values are actually calculated as an average over the two days I believe.

**Comment by davidyjeong** [comment]
btw graph reset after new year?

**Comment by trigun0x2** [comment]
@davidyjeong resets every season.

**Comment by riQQ** [comment]
Which two days? I only played on Jan 4th and one game on Jan 5th which isn't displayed in the graph. Shouldn't it only account for the days on which at least one game was played?

**Comment by trigun0x2** [comment]
@riQQ Actually it's calculated per day. Let me know if it's still halved.

**Comment by trigun0x2** [comment]
Fixed in 47e50a85a4b64ef5701ca3a76afda4714c57d58d
