### ISSUE TITLE
mistakes on the profile page

### ISSUE THREAD

**Issue by tyrcho** [HearthStats/hearthstats#433]
On [my profile](http://hearthstats.net/profiles/20273), several errors :

* the badge image is wrong (rank 13 instead of 4)
* the stats per day are wrong (I won about 90% of my matches on 11/01, not 61,40% as displayed)
* the top deck [link](http://hearthstats.net/decks/sac-pact?locale=en) is meaningless to me, it's a deck I almost never played

**Comment by trigun0x2** [comment]
-The badge refresh cron job has been erroring so I'll look into that.
-That win rate on the profile page takes the previous day's win rate into account so that it is more representative of your performance. Also it looks a lot better (instead of bouncing from 0 to 100 then to 50, etc.)
-I'm trying to find a better way to implement the "Top Deck" algorithm for sure. No good ideas so far :(

**Comment by tyrcho** [comment]
Hmmm, now the badge image was updated to rank 5, but the percentage on the badge are just different to the other stats displayed on the page.

About the stats per day, I'm surprised by what you say ... For instance on the 06 Jan, it displays 100% win with 0 games played this day. On the 5th I won 3 out of 6 games and the stats displays 85%. On the 4th I won 6 out of 9 games and it displays 75%. In short it seems almost random ...

For the top deck, I suggest to compute the average # of games per deck owned by the user, and weight the win rate by the ratio of games played to this average.
For instance :

* 10 decks, 1000 games played total so 100 average games per deck
* a deck has 100% win rate with 3 games played, it only counts as a deck with 3% win rate
* a deck has 55% win rate with 150 games played, it counts as 55% win rate
* a deck has 75% win rate win 90 games played, it counts as 75*80% = 60% so it is displayed as the top deck (with 75% win rate)

**Comment by trigun0x2** [comment]
With regards to the best deck calculations, I will try to implement it with games only in the current season.
Seems like quite a bit of calculation so I guess I'll cache it per day as well.

PS. You love Druid :P

**Comment by tyrcho** [comment]
Agreed with current season !

I'd say Druid is one of the only classes I don't s.ck too much ... but still did not get golden Druid, about 100 more games to win !

**Comment by trigun0x2** [comment]
Implemented the weight stuff here: 6d6f038
