### ISSUE TITLE
Easy way to run the uploader and point it to localhost?

### ISSUE THREAD

**Issue by jbailey** [HearthStats/hearthstats#438]
I'd like to contribute by creating some cool new reports, but I need a good way to get matches into my local database.  I forked the hearthstats uploader project but wow, that's a lot to get going.  I found where the path points to hearthstats.net api to submit matches, but I'm having troubling building the project.  

Is there an easier way to just get matching into my local database?

**Comment by trigun0x2** [comment]
Hey Jason! If your interested in doing some cool reports I have no problem
giving you limited access so you can do it off of our database.

Let me know what you think

**Comment by jbailey** [comment]
Sure, that'll work too.

**Comment by trigun0x2** [comment]
Can you send me an email with some of your ideas? Jeff@hearthstats.net

**Comment by trigun0x2** [comment]
@jbailey can we close this?

**Comment by jbailey** [comment]
Yep
