### ISSUE TITLE
Change my password

### ISSUE THREAD

**Issue by plcstevens** [HearthStats/hearthstats#447]
Hi,

I've recently been changing my passwords for sites I use and cannot seem to find the reset password link for Hearthstats. I've noticed you are using Device for account management but only have registration set in the config/routes.rb. Do you have plans to enable password reset/change?

**Comment by trigun0x2** [comment]
@plcstevens you can edit it here: https://hearthstats.net/users/edit

**Comment by trigun0x2** [comment]
e

**Comment by plcstevens** [comment]
Thanks, as a pointer is this reachable from the UI?

**Comment by trigun0x2** [comment]
Not right now mainly because it looks horrible.

**Comment by plcstevens** [comment]
;) Sure thing! Thanks for the link.
