### ISSUE TITLE
Improve view match page

### ISSUE THREAD

**Issue by Crazometer** [HearthStats/hearthstats#449]
It would be nice if the view match page could be improved to show the rank of the participants, the notes and the region the game was played in. It would be cool if I could look at others games and study them in the context of what rank the player is and what their local meta is.

I could write a push request for the rank but I am unfamiliar with ruby and it may need a little cleanup.

**Comment by trigun0x2** [comment]
Will do sir!
If you're interested on refreshing your ruby, I can also walk you through this. If not, I'll be adding rank and some other details tomorrow.

**Comment by trigun0x2** [comment]
This is completed to some degree, but there will be more to add with regards to actual stats of the match.

**Comment by trigun0x2** [comment]
This is completed to some degree, but there will be more to add with regards to actual stats of the match.

**Comment by Crazometer** [comment]
Thanks man, it's also not clear who won the match at the moment.

**Comment by trigun0x2** [comment]
Oops, I've added that now.

**Comment by Crazometer** [comment]
Sorry but one more final thing, under the player portraits could you list the players names so you can tell who wins in a mirror match? Also just incase you arent aware the turn by turn is not always accurate, particularly when the first turn is passed. 

See: http://hearthstats.net/matches/6510686?locale=en

**Comment by Crazometer** [comment]
Could you push the commit for this? I'll do whatever is left on thursday.

**Comment by trigun0x2** [comment]
@Crazometer sorry man. I just pushed it!
