### ISSUE TITLE
Delayed Job Workers Too Slow

### ISSUE THREAD

**Issue by trigun0x2** [HearthStats/hearthstats#501]
The Delayed Job workers are working slower than the actual speed of jobs being added.

https://github.com/HearthStats/hearthstats/blob/master/app/controllers/api/v3/matches_controller.rb#L96
is where the multicreate of matches happen and I've pushed it to a BG worker that uses direct SQL statements to speed it up. 
But we still currently have >1.6million jobs that need to be processed.

Any suggestions? @crawsible

**Comment by crawsible** [comment]
Yikes! I'll take a look over the weekend 👍
