### ISSUE TITLE
Automatically determining deck archetype

### ISSUE THREAD

**Issue by liujimj** [HearthStats/hearthstats#511]
Hi, I was wondering:

1. How are deck archetypes currently determined (e.g. are they hard coded or user input?)
2. Would you like any help automatically determining them?
3. If yes, is there a good call to get decks other than scraping public Deck search -> Export?

For (2), I think it would be very easy to define a distance metric on decks (e.g. edit distance between each, perhaps also weighted by how different cards are from each other (e.g. a swap from Yeti to Shredder is small distance, swap from Yeti to pyroblast is larger)), then run clustering on it and visualize the clusters + label them.

Productionizing this might be more tricky, as I would probably do this in a scientific Python distribution and not in Ruby. Let me know what you think :)

**Comment by trigun0x2** [comment]
Hey here's the current way of matching:

https://github.com/HearthStats/hearthstats/blob/master/app/models/unique_deck_type.rb#L51

Which is called from

https://github.com/HearthStats/hearthstats/blob/master/app/models/unique_deck_type.rb#L42

So right now, people automatically enter the strings to match these decks.

**Comment by liujimj** [comment]
So the strength of clustering the decks to see the archetypes would be:

1. It requires no user input
2. If a new archetype arises, you can see a new cluster
3. You can visualize the different clusters, so if a user inputs a deck, you can show things like 'this deck is really close to a standard mid-range hunter'

FYI, I'm going to do this project anyway for my own fun and edification, just wanted to know if there's a good way to pull out public decks for the raw data and if you'd be interested in the results.

**Comment by trigun0x2** [comment]
Heuristic clustering is definitely the way to go! I just never had time to implement it.

I totally support the addition of this! In this case, clustering the unique decks is the right way of doing it.

-Jeff
